language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install
  - mysqladmin create phpindonesia
  - mv build.properties.tpl build.properties
  - mv buildtime.xml.tpl buildtime.xml
  - mv connection.xml.tpl connection.xml
  - chmod -R 755 vendor/propel/
  - vendor/bin/propel-gen . diff migrate -quiet
  - vendor/bin/propel-gen -quiet
  
after_success:
  - curl -s http://dev.phpindonesia.net/synchronize

script: vendor/bin/phpunit --coverage-text

